name: Build Firmware
on:
  workflow_call:
jobs:
  Build-Firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install pipx python3-pip -y
          pipx install keymap-drawer
      - name: Setup QMK
        run: |
          python3 -m pip install --user qmk
          qmk setup -y
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Overwrite All
        run: cp -r ./* /home/runner/qmk_firmware/keyboards/boardsource/lulu/
      - name: Build Lily
        run: qmk compile -km Love-Pengy -kb boardsource/lulu/avr -e CONVERT_TO=blok
      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: lily58-firmware-Love-Pengy
          path: /home/runner/qmk_firmware/boardsource_lulu_avr_Love-Pengy_blok.uf2



