name: Visualizer Action
on: [push]
# permissions:
#   contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Create-Visualizer:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install pipx python3-pip -y
          pipx install keymap-drawer
      - name: Setup QMK
        run: |
          python3 -m pip install --user qmk
          qmk setup -y
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Overwrite All
        run: cp -r ./* /home/runner/qmk_firmware/keyboards/boardsource/lulu/
      - name: Generate JSON File
        run: qmk c2json -km Love-Pengy -kb boardsource/lulu/avr --no-cpp | keymap parse -c 12 -q - > lily_keymap_vis.yaml
      - name: Generate Visualizer
        run: |
            keymap draw lily_keymap_vis.yaml > lily_keymap_vis.svg
            rm lily_keymap_vis.yaml
      - name: Commit Visualizer
        run: |
          git pull
          git config user.name 'github-actions'
          git config user.email 'github.actions@github.com'
          git remote set-url --push origin https://Love-Pengy:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git add *.svg
          git commit -m "Add Keymap Visualizer"
          git push


